---
baseurl: "https://redcell.ai/"
languageCode: "en-us"
copyright: "Redcell, Pittsburgh, PA"
title: "Redcell Talent Accelerator"
theme: "hugo-insomnia-theme"
publishdir: "public"
disqusShortname: "redcell-talent"
googleAnalytics: "UA-113582687-1"
permalinks:
  blog: /blog/:slug
menu:
  main:
    - Name: "Connect"
      Identifier: "connect"
      URL: "/support/"
      Weight: 1
    # - Name: "Pricing"
    #   Identifier: "pricing"
    #   URL: "/pricing/"
    #   Weight: 2
    - Name: "Blog"
      Identifier: "blog"
      URL: "/blog/"
      Weight: 2
    - Name: "Blockchain Demo"
      Identifier: "blockchain"
      Pre: "button"
      URL: "http://blockchain.redcell.ai"
      Weight: 4
    # - Name: "Account"
    #   Identifier: "account"
    #   Pre: "button"
    #   URL: "/app/account/"
    #   Weight: 5
    # - Name: "Sign Up"
    #   Identifier: "signup"
    #   Pre: "button"
    #   URL: "/app/signup/"
    #   Weight: 99
    - Name: "Learn More"
      Identifier: "download"
      URL: /support/
      Weight: 100
  footer:
    - Name: "Blockchain Demo"
      Identifier: "blockchain"
      Pre: "button"
      URL: "http://blockchain.redcell.ai"
      Weight: 3
    - Name: Contact
      Identifier: support
      URL: /support/
      weight: 4
    - Name: Terms
      Identifier: terms
      URL: /terms/
      weight: 100
    - Name: Privacy
      Identifier: privacy
      URL: /privacy/
      weight: 100
author:
  name: "Daniel Nichols"
  image: "me.jpg"
taxonomies:
  tag: "tags"
  category: "categories"
  series: "series"
params:
  copyrightURL: "https://redcell.ai"
  repo: "git@gitlab.com:tripleorange/redcell.git"
  docsCategories:
    - "welcome"
    - "starting"
    - "topics"
  stylesheets:
    - "main.css"
  scripts:
    - "build/main.min.js"
  email: "contact@redcell.ai"
  pageNotFoundTitle: "Sorry, that page doesn't exist"
  # shortName: ""
  bio: "Talent Accelerator"
  location: "Pittsburgh, PA"
  description: "Powerful talent accelerator delivering improved ROI to clients through cookie management, environment variables, code generation, and authentication for Mac, Window, and Linux"
  keepReadingStr: "Read More"
pygmentsCodeFences: true
pygmentsStyle: "monokai"
pygmentsUseClasses: true
metaDataFormat: "yaml"
blackfriday:
  fractions: false
